name: Auto Approve, Merge, and Deploy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    needs: auto-approve
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Auto merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /home/zbara/www/code-hub && sh deploy.sh"
